
services:
   database:
      image: postgres
      networks:
         - backend
      environment:
         POSTGRES_PASSWORD: jobman 
         POSTGRES_USER: jobman 
         POSTGRES_DB: jobman 

   mock-cache:
      build: ./mock-cache
      networks:
         - backend
      ports:
         - "5001:80"
      environment:
         CAPTURE_OUTPUT: "True"
         ACCESS_LOG_FILE: "-"
         ERROR_LOG_FILE: "-"

   mock-source:
      build: ./mock-source
      networks:
         - backend
      ports:
         - "5002:80"
      environment:
         CAPTURE_OUTPUT: "True"
         ACCESS_LOG_FILE: "-"
         ERROR_LOG_FILE: "-"

   job-manager:
      build: ..
      networks:
         - backend
      ports:
         - "5000:80"

      environment:
         DATA_CACHE_URL: http://mock-cache
         ROUTER_URL: http://mock-source
         DATABASE_CONNECTION_STRING: postgresql://jobman:jobman@database:5432/jobman
         LOG_LEVEL: debug 
         CAPTURE_OUTPUT: "True"
         ERROR_LOG_FILE: "-"
      depends_on:
         - database
         - mock-cache 
         - mock-source 

networks:
  backend:
